### PR TITLE
Write first tests

### PR DESCRIPTION
**Pull request by ostcar**
I have a really hard time to write tests for channels2. So I though it might be a good idea to have some example tests.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I agree, though if they're going to go in the examples repo I'd like to see more comments on them :)

**Comment by ostcar** [comment]
You are right. I will add some in the next two weeks (don't have time at before).

Would you also accept a pull request in the channels repo, that would make the user authentication with the WebsocketCommunicator and HTTPCommunicator a bit easier? For example with a new optional attribute 'user' that creates or reuses a session for a user object?
```python
user = User.objects.create(username='user1')
WebsocketCommunicator(application, "/chat/stream/", user=user)
```

**Comment by andrewgodwin** [comment]
@ostcar I thought there was already something like that on the communicators? I definitely remember there already being an issue/discussion about it before.

**Comment by slyapustin** [comment]
@ostcar Here some workaround for that: https://github.com/django/channels/issues/903#issuecomment-368412478

```python
communicator = WebsocketCommunicator(Consumer, "/")
communicator.scope['user'] = user
```

**Comment by ostcar** [comment]
Cleaning up my old PRs. If someone else wants to add this code, feal free to copy it and start a new pr

**Pull request closed without merging**
